name: compile assets

on:
  workflow_call:
    inputs:
      nodejs:
        type: string
        default: '20.x'
      gpg_bot_token:
        required: true
        type: string
        description: bot gpg token
      gpg_passphrase:
        required: true
        type: string
        description: bot gpg passphrase
      gpg_fingerprint:
        required: true
        type: string
        description: bot gpg fingerprint
      github_bot_token:
        required: true
        type: string
        description: bot token

jobs:
  compile:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node ${{ inputs.nodejs }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodejs }}
          cache: npm

      - name: "install"
        run: npm ci --production

      - name: "build"
        run: npm run build

      - name: "Check if build has changed"
        if: success()
        id: has-changes
        run: |
          echo "stdout<<EOF" >> $GITHUB_OUTPUT
          echo "$(git diff  --stat)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Import GPG key
        if: ${{ steps.has-changes.outputs.stdout }}
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ inputs.gpg_bot_token }}
          passphrase: ${{ inputs.gpg_passphrase }}
          fingerprint: ${{ inputs.gpg_fingerprint }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: Github bot
          git_committer_email: bot@babichev.net

      - name: "Commit files"
        if: ${{ steps.has-changes.outputs.stdout }}
        env:
          GH_TOKEN: ${{ inputs.github_bot_token }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git commit -S -m "build action" -a

      - name: "Push changes"
        if: ${{ steps.has-changes.outputs.stdout }}
        env:
          GITHUB_TOKEN: ${{ inputs.github_bot_token }}
        run: git push -u origin HEAD
