name: go semgrep

on:
  workflow_call:

jobs:
  semgrep:
    name: Check semgrep
    runs-on: ubuntu-latest
    container:
      image: bavix/semgrep:master
    steps:
      - uses: actions/checkout@v5
      - name: "Run semgrep"
        run: semgrep scan --error --config=p/golang -f /semgrep-go
