---
name: rust-cargo-deny

'on':
  'workflow_call':
    inputs:
      working-directory:
        type: string
        default: '.'
      deny-config:
        type: string
        default: 'deny.toml'
      checks:
        type: string
        default: 'check'
      cargo-deny-version:
        type: string
        default: 'latest'

jobs:
  deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@${{ inputs.cargo-deny-version }}

      - name: Run cargo deny
        working-directory: ${{ inputs.working-directory }}
        run: cargo deny ${{ inputs.checks }} --config ${{ inputs.deny-config }}
