---
name: security-scan

on:
  'workflow_call':
    inputs:
      go-version:
        type: string
        default: '1.26'
      working-directory:
        type: string
        default: '.'
      gosec-enabled:
        type: boolean
        default: true
      trivy-enabled:
        type: boolean
        default: true
      trivy-scan-type:
        type: string
        default: 'fs'
      trivy-scan-ref:
        type: string
        default: '.'
      trivy-format:
        type: string
        default: 'sarif'
      trivy-severity:
        type: string
        default: 'CRITICAL,HIGH'
      gosec-version:
        type: string
        default: 'latest'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        if: ${{ inputs.gosec-enabled }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          cache: true
          cache-dependency-path: ${{ inputs.working-directory }}/go.sum

      - name: Run gosec
        if: ${{ inputs.gosec-enabled }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@${{ inputs.gosec-version }}
          gosec -no-fail -fmt sarif -out gosec-report.sarif ./...

      - name: Upload gosec results
        if: ${{ inputs.gosec-enabled }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ inputs.working-directory }}/gosec-report.sarif

      - name: Run Trivy vulnerability scanner
        if: ${{ inputs.trivy-enabled }}
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: ${{ inputs.trivy-scan-type }}
          scan-ref: ${{ inputs.trivy-scan-ref }}
          format: ${{ inputs.trivy-format }}
          output: 'trivy-results.sarif'
          severity: ${{ inputs.trivy-severity }}

      - name: Upload Trivy scan results
        if: ${{ inputs.trivy-enabled }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
